// <auto-generated />
using MonoTouch.Foundation;

namespace AkvelonContacts.iOS
{
    [Register("AkvelonContactsViewController")]
    partial class AkvelonContactsViewController
    {
        void ReleaseDesignerOutlets()
        {
        }
    }
}