//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkvelonContacts.WindowsPhone {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AkvelonContacts.WindowsPhone.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to contact.
        /// </summary>
        public static string AddContactButtonText {
            get {
                return ResourceManager.GetString("AddContactButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to akvelon contacts.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call contact.
        /// </summary>
        public static string CallButtonText {
            get {
                return ResourceManager.GetString("CallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dislocation.
        /// </summary>
        public static string DislocationTitleText {
            get {
                return ResourceManager.GetString("DislocationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string EmailTitleText {
            get {
                return ResourceManager.GetString("EmailTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сontact with the same name exists. Please rename the contact to avoid an unexpected result..
        /// </summary>
        public static string MessageIfContactAlreadyExists {
            get {
                return ResourceManager.GetString("MessageIfContactAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load contacts. Please check your internet connection..
        /// </summary>
        public static string MessageIfContactsNotLoaded {
            get {
                return ResourceManager.GetString("MessageIfContactsNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact list is not available..
        /// </summary>
        public static string MessageIfSearchWithoutContacts {
            get {
                return ResourceManager.GetString("MessageIfSearchWithoutContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneTitleText {
            get {
                return ResourceManager.GetString("PhoneTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string RefreshButtonTitleOfAppBar {
            get {
                return ResourceManager.GetString("RefreshButtonTitleOfAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchBackgroundText {
            get {
                return ResourceManager.GetString("SearchBackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchButtonTitleOfAppBar {
            get {
                return ResourceManager.GetString("SearchButtonTitleOfAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send emile.
        /// </summary>
        public static string SendEmileButtonText {
            get {
                return ResourceManager.GetString("SendEmileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS.
        /// </summary>
        public static string SendSmsButtonText {
            get {
                return ResourceManager.GetString("SendSmsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show all contacts.
        /// </summary>
        public static string ShowAllContactsItemMenuText {
            get {
                return ResourceManager.GetString("ShowAllContactsItemMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show contacts with keys.
        /// </summary>
        public static string ShowContactsWithKeyItemMenuText {
            get {
                return ResourceManager.GetString("ShowContactsWithKeyItemMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string SkypeTitleText {
            get {
                return ResourceManager.GetString("SkypeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
